# 05: Full NEM 2 investment periods [2030, 2050].

paths:
  run_directory: "analysis/benchmarks/runs"
  ispypsa_run_name: bench_05_nem_2period
  parsed_traces_directory: "analysis/data/traces"
  workbook_path: "analysis/data/iasr_2024_v6.0.xlsx"
  parsed_workbook_cache: "analysis/data/workbook_cache"

trace_data:
  dataset_type: example
  dataset_year: 2024

iasr_workbook_version: "6.0"
scenario: Step Change
wacc: 0.07
discount_rate: 0.05
unserved_energy:
  cost: 10000.0
  max_per_node: 100000.0

network:
  transmission_expansion: True
  rez_transmission_expansion: True
  annuitisation_lifetime: 30
  nodes:
    regional_granularity: sub_regions
    rezs: discrete_nodes
  rez_to_sub_region_transmission_default_limit: 1e5

temporal:
  year_type: fy
  range:
    start_year: 2030
    end_year: 2050
  capacity_expansion:
    resolution_min: 30
    reference_year_cycle: [2018]
    investment_periods: [2030, 2050]
    aggregation:
      representative_weeks: ~
      named_representative_weeks: [residual-peak-demand]
  operational:
    resolution_min: 30
    reference_year_cycle: [2018]
    horizon: 336
    overlap: 48
    aggregation:
      representative_weeks: ~
      named_representative_weeks: [residual-peak-demand]

solver: highs
create_plots: False
